config/routes.rb
Rails.application.routes.draw do
  
	root to: 'events#index'

	get 'users/new' => 'users#new', as: :new_user
	post 'users' => 'users#create'
	
	# ----- add these lines here: -----
	
	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  

resources :users
resources :events  	  	
  	# ----- end of added lines -----

  
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: :User
    has_many :invitations,foreign_key: :attended_event_id
    has_many :attendees, through: :invitations , source: :attendee
    
    default_scope { order("created_at DESC") }
    scope :upcoming_events, -> {where("date >= ?",DateTime.now)}
    scope :prev_events, -> {where("date < ?",DateTime.now)}
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	belongs_to :attendee, class_name: :User,foreign_key: :attendee_id
    belongs_to :attended_event, class_name: :Event,foreign_key: :attended_event_id
end

app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	has_many :events, foreign_key: :creator_id
	has_many :invitations, foreign_key: :attendee_id
    has_many :attended_events,through: :invitations , source: :attended_event

	# ----- end of added lines -----
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # ----- add these lines here: -----

  # Make the current_user method available to views also, not just controllers:
  helper_method :current_user
  
  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # ----- end of added lines -----

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
  	@event = Event.new
  end

  def create
  	# @event = Event.new(event_params)
  	@user = current_user
  	@event = @user.events.create(event_params)
  	if @event.save
      flash[:notice] = "Event created successfully!"
      redirect_to @user
   else
      flash.now.alert = "Oops, couldn't create Event. Please make sure you are using a valid description."
      render :new
   end
  end

  def show
  	@event = Event.find(params[:id])
  	@user = current_user
  end

  def index
  	@events = Event.all
    @upcoming_events = @events.upcoming_events  
    @prev_events = @events.prev_events
  end

private

  def event_params
  	params.require(:event).permit(:description, :date)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# ----- add these lines here: -----

  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
      user = User.find_by(email: params[:login][:email].downcase)
    
    # Verify user exists in db and run has_secure_password's .authenticate() 
    # method to see if the password submitted on the login form was correct: 
    if user && user.authenticate(params[:login][:password]) 
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    # delete the saved user_id key/value from the cookie:
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
  
# ----- end of added lines -----
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:notice] = "Account created successfully!"
      redirect_to root_path
   else
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
   end
  end

  def show
  	@user = current_user
    @upcoming_events = current_user.events.upcoming_events  
    @prev_events = current_user.events.prev_events
  end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1> All Events </h1>
<ul>
	<% @events.each do |e| %>
	<li>Event Description: <%= e.description %></li>
	<li>Event Date: <%= e.date %></li>
	<div> <p> </p>
	</div>
	<% end %>
</ul>

<h1> Upcoming </h1>
<ul>
	<% @upcoming_events.each do |e| %>
	<li>Event Description: <%= e.description %></li>
	<li>Event Date: <%= e.date %></li>
	<div> <p> </p>
	</div>
	<% end %>
</ul>
<div>
	</div>
<h1> Previous Events </h1>
<ul>
	<% @prev_events.each do |e| %>
	<li>Event Description: <%= e.description %></li>
	<li>Event Date: <%= e.date %></li>
	<div> <p> </p>
	</div>
	<% end %>
</ul>

app/views/events/new.html.erb
<%= form_for @event do |f| %>

  <%= f.label 'description' %>
  <%= f.text_field :description %>
  <br /> <br />

 <%= f.label 'date' %>
  <%= f.date_field :date %>
  <br /> <br />

  <%= submit_tag "#{@event.new_record? ? 'Create' : 'Update'} Post" %>

<% end %>

app/views/events/show.html.erb
<h2>Event Description: <%= @event.description %></h2>
<h4>Event Date: <%= @event.description %></h4>
<h4>Event Attendees: <%= @event.attendees %></h4>
<div>

<p>Host: <%= @user.first_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
   <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
    <hr>

  <% if notice %>
            <%= notice %>
  <% end %>
  
  <% if alert %>
            <%= alert %>
  <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%# ----- add these lines here: ----- %>

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %>

<h1> Hosted Events: <h1>
<h4><% @user.events.each do |e| %></h4>
<h2> Description: <%= e.description %> </h1>
<h4> Date: <%= e.date %> </h4>
<% end %>


<h1>Upcoming:</h1>

<h4>Upcoming Events : <%= @user.events.upcoming_events.each do |e| %></h4>
<h2> Description: <%= e.description %> </h1>
<h4> Date: <%= e.date %> </h4>
<% end %>

<h1>Previously Attended:</h1>

<h4>Events Attended : <%= @user.events.prev_events.each do |e| %></h4>
<h2> Description: <%= e.description %> </h1>
<h4> Date: <%= e.date %> </h4>
<% end %>